### ISSUE TITLE
Event Sourcing Support

### ISSUE THREAD

**Issue by vmorugin** [dddmisc/dddmisc#7]
This library seems like an almost complete solution for implementing event sourcing. However, there are several improvements that may be beneficial to discuss and potentially integrate into the domain model or factor out into a separate module. These improvements are as follows:

## Ordered Event Collection
Currently, events are stored in a set, which does not preserve order. It is essential that the collect_event method within the domain model ensures the order in which events are registered. This ordering is critical for correctly reconstituting aggregates from event histories.

## resolve Method for DomainObjectsCollection
If events are stored in a database, we need to be able to handle older versions of events effectively. For example, if a class name for an event changes, there should be a way to map an old name to a new class. Implementing a resolve method would allow us to manage legacy events while maintaining compatibility.

## Enhancement of the Base Domain Event Class
We need to further develop the base class for domain events. Specifically, it should include methods that update the aggregate state according to the event details. Below is an example implementation of the mutate and apply methods:

```python

class DomainEvent(BaseDomainMessage, AbstractEvent, metaclass=_DomainEventMeta):
    originator_reference: UUID = Field(exclude=True)
    originator_version: Version = Field(exclude=True)

    def mutate(self, aggregate: RootEntity | None) -> RootEntity | None:
        assert aggregate is not None

        # Check this event belongs to this aggregate.
        assert aggregate.__reference__ == self.originator_reference

        # Check this event is the next in its sequence.
        next_version = aggregate.__version__ + 1
        assert self.originator_version == next_version

        # Call apply() before mutating values, in case exception is raised.
        self.apply(aggregate)

        # Update the aggregate's 'originator_version' number.
        increment_version(aggregate)

        # Update the aggregate's 'modified on' time.
        # aggregate.modified_on = self.timestamp

        # Return the mutated aggregate.
        return aggregate

    def apply(self, aggregate: RootEntity) -> None:
        ...

class RootEntity(
    Entity,
    IRootEntity,
    Generic[_ReferenceType],
    metaclass=_RootEntityMeta,
):
    __version: Version = Version(1)

    def __init_subclass__(cls, *, domain: str | None = None, **kwargs):
        super().__init_subclass__()

    def __init__(self, **data):
        super().__init__(**data)
        self._events: list[AbstractEvent] = list()

    @property
    def __domain_name__(self) -> DomainName:
        """
        Get the domain name associated with the current class.

        Returns:
            DomainName: The domain name associated with the class.

        """
        return self.__class__.__domain_name__  # type: ignore

    @property
    def __version__(self) -> Version:
        """
        Get the current originator_version of the root entity.

        Returns:
             Version: The current originator_version of the root entity.
        """
        return self.__version

    def create_event(self, __name: MessageName | str, /, **payload):
        increment_version(self)
        event_class = get_event_class(self.__domain_name__, __name)
        event = event_class(
            originator_reference=self.__reference__,
            originator_version=self.__version__,
            **payload,
        )
        event.apply(self)
        self._events.append(event)

    def collect_events(self) -> Iterable[DomainEvent]:
        events = self._events
        self._events = []
        yield from events

```
The mutate method ensures that the event is correctly applied to the aggregate while verifying the event sequence and the aggregate’s state. This design helps maintain consistency in event-sourced aggregates.

**Comment by vvorobyov** [comment]
Hi, @vmorugin. This is a very good suggestion, but in the current implementation of the `dddmisc-domain` package, the idea of DomainEvent was laid down as a way of communication between the domain model and the world outside of it, which in my opinion is somewhat different from the ideas laid down in event sourcing. Your suggestion looks like a good start to develop an alternative approach to domain implementation that can be used instead of `dddmisc-domain`.  When developing the project, I first of all took care of the availability of such an opportunity, and I will be glad if these solutions begin to be released.  Unfortunately, I have no plans in the foreseeable future to support Event Sourcing within the framework of current implementations.
 I will gladly accept the PR into the shared repository or give a link to your implementation in the README and documentation as part of the package family dddmisc.
